[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tools.isort]
profile = "black"
multi_line_output = 3
known_third_party = ["click", "environs", "pytest", "requests", "setuptools", "xlsxwriter"]
